### ISSUE TITLE
Git Bash isn't available to all accounts

### ISSUE THREAD

**Issue by Joedang** [psas/workstations#2]
It seems that not all Windows accounts (@E-Ruhl at least) have access to Git Bash. They only have GitHub Desktop. It should really be the opposite of that. The CLI should be the default and the GUI should be available upon request. This is because the _vast majority_ of people in PSAS use Git from the command line and the workshops are only taught through Bash. (Personally, I like this, since too many MMEs are scared of CLIs and need to get over it.) If people can only use a GUI by default, they can't get help from others and they can't use a lot of the info from the workshops.

**Comment by haneefmubarak** [comment]
I don't remember installing Git Bash at any point and I don't remember you installing it either. IIRC, GitHub Desktop lets you install command line tools from within the interface and that's essentially Git Bash (on Windows).

I'll check and update this.

**Comment by haneefmubarak** [comment]
Interesting...

Apparently they _used_ to include it in GitHub desktop (which is what I remembered it from), but they discontinued that two years ago.

Where did your install come from?

**Comment by haneefmubarak** [comment]
Meanwhile, I have installed Git for Windows and confirmed that it works.

**Comment by Joedang** [comment]
I think mine came with Git for Windows.

**Comment by haneefmubarak** [comment]
Huh. I'll look further into that, but until then, Git Bash should work for everyone.

You might have a local install of some sort.
