### ISSUE TITLE
Password timeouts on Windows accounts

### ISSUE THREAD

**Issue by Joedang** [psas/workstations#3]
@andrewgreenberg needs a password reset for his Windows account on the CAD workstation. (I'm guessing this is from the password timeouts.) 

I don't know if the timeouts are a global thing, or if they're for individual accounts. I'm guessing there are going to be a few more people who can't log in, besides CJT. If anyone else is still subject to a password timeout, that should be removed. Otherwise, no one's going to be able to use that thing...

**Comment by haneefmubarak** [comment]
IIRC last time we had an issue I went through and disabled all of the timeouts. We should be good. I'm 99% sure that @andrewgreenberg just forgot his password.

**Comment by haneefmubarak** [comment]
Also @Joedang who is CJT?
